# Visual Shop Configuration File

enabled: true
debug: false

#The time betwwen two shop's update in seconds
#An update refix the item entity's position
#Bigger then number is, faster is the plugin, but item entities' postion may be buggier 
update-time: 60

#Protect shops from explosions ans entities
protect-shops: true
