main: fr.mathdu07.visualshop.VisualShop
version: 1.0.2
name: VisualShop
description: A basic plugin to sell items as administrator
author: mathdu07
depend: [Vault]
commands:
  visualshop:
    description: Main command for the VisualShop plugin
    aliases: [vs, shop]
permissions:
  visualshop.*:
    description: Give all permission of the plugin
    default: false
    children:
      visualshop.admin.*: true
      visualshop.common.*: true
  visualshop.admin.*:
    description: Give all admin permissions
    default: op
    children:
      visualshop.admin.reload: true
      visualshop.admin.toggle: true
      visualshop.admin.create.*: true
      visualshop.admin.delete: true
  visualshop.admin.reload:
    description: Allow to reload the plugin configurations
    default: op
  visualshop.admin.toggle:
    description: See the current toggled params or set its
    default: op
  visualshop.admin.toggle.advanced:
    description: See if advanced is toggled, or set it
    default: op
  visualshop.admin.create.*:
    description: Allow to create admin shops
    default: op
    children:
      visualshop.admin.create.sell: true
      visualshop.admin.create.buy: true
  visualshop.admin.create.sell:
    description: Allow to create admin sell shops
    default: op
  visualshop.admin.create.buy:
    description: Allow to create admin buy shops
    default: op
  visualshop.admin.delete:
    description: Give the ability to delete any type of shops
    default: op
  visualshop.common.*:
    description: Give all the common abilities
    default: true
    children:
      visualshop.common.use: true
      visualshop.common.undo: true
      visualshop.common.create.*: true
      visualshop.common.sign: true
  visualshop.common.use:
    description: Give the ability to use any type of shops
    default: true
  visualshop.common.undo:
    description: Give the ability to undo previous transactions
    default: true
  visualshop.common.create.*:
    description: Give the ability to create player shops
    default: true
    children:
      visualshop.common.create.sell: true
      visualshop.common.create.buy: true
  visualshop.common.create.sell:
    description: Allow to create player sell shops
    default: true
  visualshop.common.create.buy:
    description: Allow to create player buy shops
    default: true
  visualshop.common.sign:
    description: Auto complete the sign when placed against a shop
    default: true
